task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 8
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # img_folder: /workspace/suan/TOD/data/ai-tod/AI-TOD/aitodtoolkit/aitod/images/train
    # ann_file: /workspace/suan/TOD/data/ai-tod/AI-TOD/aitodtoolkit/aitod/annotations/complete_annotations_v2/aitodv2_train.json
    img_folder: /workspace/suan/TOD/data/ai-tod_sample/images/train
    ann_file: /workspace/suan/TOD/data/ai-tod_sample/annotations/aitodv2_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    # img_folder: /workspace/suan/TOD/data/ai-tod/AI-TOD/aitodtoolkit/aitod/images/val
    # ann_file: /workspace/suan/TOD/data/ai-tod/AI-TOD/aitodtoolkit/aitod/annotations/complete_annotations_v2/aitodv2_val.json
    img_folder: /workspace/suan/TOD/data/ai-tod_sample/images/val
    ann_file: /workspace/suan/TOD/data/ai-tod_sample/annotations/aitodv2_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction